# Generated by Django 5.2.17 on 2026-09-01 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "base_model",
                    models.CharField(
                        choices=[
                            ("unit_asset", "Assets"),
                            ("stock_balance", "Stock Balances"),
                            ("transaction", "Transactions"),
                            ("transaction_line", "Transaction Lines"),
                            ("status_history", "Asset Status History"),
                        ],
                        max_length=20,
                    ),
                ),
                ("selected_fields", models.JSONField(blank=True, default=list)),
                ("filters", models.JSONField(blank=True, default=list)),
                ("is_shared", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
