# Generated by Django 5.2.17 on 2026-09-05 11:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataQualityFinding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("dedup_key", models.CharField(editable=False, max_length=200, unique=True)),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("duplicate_serial", "Duplicate serial number"),
                            ("missing_location", "Missing location"),
                            ("missing_custodian", "Missing custodian"),
                            (
                                "serialized_asset_without_serial",
                                "Serialized asset without a serial number",
                            ),
                            ("invalid_balance", "Stock balance for an inactive product"),
                            ("stale_custody_pointer", "Stale custody pointer"),
                            (
                                "customer_stock_missing_reference",
                                "Customer stock missing customer/project reference",
                            ),
                            (
                                "inactive_location_with_active_stock",
                                "Inactive location with active stock",
                            ),
                            ("invalid_location_hierarchy", "Invalid location hierarchy"),
                            ("missing_procurement_info", "Missing procurement information"),
                            ("duplicate_product", "Duplicate or potential-duplicate product"),
                            ("orphaned_transaction_reference", "Orphaned transaction reference"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=64)),
                ("country", models.CharField(blank=True, max_length=120)),
                ("location_label", models.CharField(blank=True, max_length=255)),
                ("explanation", models.TextField()),
                ("recommended_correction", models.TextField(blank=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "-detected_at"],
                "indexes": [
                    models.Index(fields=["status"], name="dqfinding_status_idx"),
                    models.Index(fields=["issue_type"], name="dqfinding_issue_type_idx"),
                    models.Index(fields=["country"], name="dqfinding_country_idx"),
                    models.Index(fields=["object_type", "object_id"], name="dqfinding_object_idx"),
                ],
            },
        ),
    ]
