# Generated by Django 5.2.17 on 2026-09-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataquality", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataqualityfinding",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("duplicate_serial", "Duplicate serial number"),
                    ("missing_location", "Missing location"),
                    ("missing_custodian", "Missing custodian"),
                    ("serialized_asset_without_serial", "Serialized asset without a serial number"),
                    ("invalid_balance", "Stock balance for an inactive product"),
                    ("stale_custody_pointer", "Stale custody pointer"),
                    (
                        "customer_stock_missing_reference",
                        "Customer stock missing customer/project reference",
                    ),
                    ("inactive_location_with_active_stock", "Inactive location with active stock"),
                    ("invalid_location_hierarchy", "Invalid location hierarchy"),
                    ("missing_procurement_info", "Missing procurement information"),
                    ("duplicate_product", "Duplicate or potential-duplicate product"),
                    ("orphaned_transaction_reference", "Orphaned transaction reference"),
                    ("country_only_location", "Stock held above Storage Room level"),
                ],
                max_length=40,
            ),
        ),
    ]
