# Generated by Django 5.2.17 on 2026-08-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_documenttemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="accent_color",
            field=models.CharField(default="#444444", max_length=7),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="font_choice",
            field=models.CharField(
                choices=[("sans", "Sans-serif"), ("serif", "Serif"), ("mono", "Monospace")],
                default="sans",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="logo_position",
            field=models.CharField(
                choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                default="left",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="page_margin",
            field=models.CharField(
                choices=[("compact", "Compact"), ("normal", "Normal"), ("spacious", "Spacious")],
                default="normal",
                max_length=10,
            ),
        ),
    ]
