# Generated by Django 5.2.17 on 2026-09-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_documenttemplate_accent_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttemplate",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("assignment", "Assignment"),
                    ("delivery", "Delivery"),
                    ("disposal", "Disposal certificate"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="generateddocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("assignment", "Assignment"),
                    ("delivery", "Delivery"),
                    ("disposal", "Disposal certificate"),
                ],
                max_length=20,
            ),
        ),
    ]
