# Generated by Django 5.2.17 on 2026-09-04 19:11

import apps.documents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_alter_documenttemplate_document_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="layout_config",
            field=models.JSONField(default=apps.documents.models._default_layout_config),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Bumped on every save (apps.documents.template_services.update_template) — the value snapshotted onto GeneratedDocument.template_version at generation time, so a historical document can always name exactly which configuration produced it.",
            ),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Which DocumentTemplate row (if any — the packaged default has none) actually rendered this PDF. SET_NULL, not PROTECT: a later reset/reconfigure of that template must never be blocked by history that already has its own frozen context_snapshot and pdf_file — this FK is a convenience pointer, not the source of truth for what was printed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_documents",
                to="documents.documenttemplate",
            ),
        ),
        migrations.AlterField(
            model_name="generateddocument",
            name="template_version",
            field=models.CharField(
                help_text="A human-readable snapshot of the template's version at generation time — 'form_v1' for the packaged default, or 'v<N>' from DocumentTemplate.version when an Administrator-configured template rendered this document.",
                max_length=40,
            ),
        ),
    ]
