# Generated by Django 5.2.17 on 2026-09-06 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_add_layout_config_and_template_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "field_snapshot",
                    models.JSONField(
                        help_text="html_source, style fields, document_title/company fields, and layout_config at the moment this version was saved — enough to fully restore the configuration."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="company_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="company_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="company_tax_id",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="document_title",
            field=models.CharField(
                blank=True,
                help_text="Overrides the auto-derived movement-type heading (e.g. 'Customer delivery') when set. Plain text — escaped like any other template variable, never HTML.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="heading_text_color",
            field=models.CharField(
                blank=True,
                help_text="#rrggbb, or blank to reuse the accent color (matches today's behavior).",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="False once reset/replaced — hidden everywhere but still resolvable by any GeneratedDocument that already references it.",
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="section_spacing",
            field=models.CharField(
                choices=[("compact", "Compact"), ("normal", "Normal"), ("spacious", "Spacious")],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="table_header_bg_color",
            field=models.CharField(
                blank=True,
                help_text="#rrggbb, or blank to keep the packaged default light-grey header row.",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("assignment", "Assignment"),
                    ("delivery", "Delivery"),
                    ("disposal", "Disposal certificate"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Bumped on every save (apps.documents.template_services.update_template) — the value snapshotted onto GeneratedDocument.template_version at generation time, and matching the DocumentTemplateVersion row created alongside it, so a historical document can always name exactly which configuration produced it.",
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("document_type",),
                name="one_active_template_per_type",
            ),
        ),
        migrations.AddField(
            model_name="documenttemplateversion",
            name="saved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documenttemplateversion",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="documents.documenttemplate",
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version"), name="unique_template_version"
            ),
        ),
    ]
