# Generated by Django 5.2.17 on 2026-09-06 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_documenttemplateversion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentIntegrityCheckRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                ("checked_count", models.PositiveIntegerField()),
                (
                    "missing_document_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="GeneratedDocument ids whose pdf_file was missing, empty, or not a valid PDF.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRenderLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("assignment", "Assignment"),
                            ("delivery", "Delivery"),
                            ("disposal", "Disposal certificate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("template_version", models.CharField(blank=True, max_length=40)),
                ("duration_ms", models.PositiveIntegerField()),
                ("success", models.BooleanField()),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null when the render failed outright — never a document to point to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="render_log",
                        to="documents.generateddocument",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null means the packaged default rendered it (no override existed at the time).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="render_logs",
                        to="documents.documenttemplate",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["success", "created_at"], name="renderlog_success_created_idx"
                    )
                ],
            },
        ),
    ]
