# Generated by Django 5.2.17 on 2026-09-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_documentintegritycheckrun_documentrenderlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="logo_intentionally_omitted",
            field=models.BooleanField(
                default=False,
                help_text="Acknowledges this template has no logo on purpose — lets the completeness checklist pass without one, instead of treating a blank logo as an oversight forever.",
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="preview_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Set only by explicitly ticking the editor's confirmation checkbox on a save; any subsequent save resets it — an Administrator must re-review the PDF preview after every change before Publish is allowed.",
            ),
        ),
    ]
