# Generated by Django 5.2.17 on 2026-09-06 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_documenttemplate_logo_intentionally_omitted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who approved and published this configuration — always a different Administrator from submitted_by.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who submitted this configuration for review — cleared whenever a subsequent edit reverts the row back to Draft.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending review"),
                    ("published", "Published"),
                ],
                default="draft",
                max_length=14,
            ),
        ),
    ]
