# Generated by Django 5.2.17 on 2026-09-06 14:51

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_documenttemplate_approved_at_and_more"),
        ("locations", "0002_location_path_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryBrandingProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.documents.models._branding_logo_upload_path,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("company_address", models.TextField(blank=True)),
                ("company_tax_id", models.CharField(blank=True, max_length=60)),
                (
                    "terms_text",
                    models.TextField(
                        blank=True,
                        help_text="Overrides the document type's own terms and conditions wording.",
                    ),
                ),
                ("signature_left_label", models.CharField(blank=True, max_length=120)),
                ("signature_right_label", models.CharField(blank=True, max_length=120)),
                (
                    "country",
                    models.OneToOneField(
                        help_text="Must be a Country-level location.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branding_profile",
                        to="locations.location",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
