# Generated by Django 5.2.17 on 2026-09-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_countrybrandingprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="custom_html_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When set, html_source is an Administrator's hand-typed HTML/CSS instead of being auto-composed from the structured fields above (apps.documents.pdf.render_styleable_source()) — see this model's docstring for what stays safe either way.",
            ),
        ),
    ]
