# Generated by Django 5.2.17 on 2026-08-24 14:18

import apps.locations.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ltree type must exist before a column of that type can be created.
        ("core", "0001_enable_ltree"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("country", "Country"),
                            ("site", "Site/Building"),
                            ("floor", "Floor"),
                            ("storage_room", "Storage Room"),
                            ("rack_cabinet", "Rack/Cabinet"),
                            ("shelf_bin", "Shelf/Bin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(blank=True, max_length=30)),
                ("path", apps.locations.fields.LtreeField(blank=True, editable=False, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["level", "is_active"], name="location_level_active_idx"),
                    models.Index(fields=["name"], name="location_name_idx"),
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["path"], name="location_path_gist_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("level", "country"), ("parent__isnull", True)),
                            models.Q(
                                models.Q(("level", "country"), _negated=True),
                                ("parent__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="location_country_has_no_parent",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        condition=models.Q(("level", "country")),
                        name="location_unique_country_name",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        models.F("parent"),
                        models.F("level"),
                        condition=models.Q(("level", "country"), _negated=True),
                        name="location_unique_sibling_name",
                    ),
                ],
            },
        ),
    ]
