# Generated by Django 5.2.17 on 2026-09-07 09:48, hand-extended to collapse
# the six-level Location hierarchy (Country/Site/Floor/Storage Room/
# Rack-Cabinet/Shelf-Bin) down to three (Country/Storage Room/Rack-Shelf) —
# by direct instruction: Site and Floor added authorization-boundary depth
# nobody used, and Rack/Cabinet vs Shelf/Bin was a distinction without a
# difference for how stock is actually tracked.
#
# No Location row, UnitAsset/StockBalance placement, or ledger history is
# deleted or re-keyed — every existing Storage Room and Rack/Shelf keeps its
# own id and everything that references it. Only three things change:
#   1. Every Storage Room whose parent was a Site/Floor is re-parented
#      directly onto its Country ancestor.
#   2. Every Rack/Cabinet or Shelf/Bin (regardless of how deeply nested,
#      since a Shelf could sit under a Rack) becomes a direct child of its
#      enclosing Storage Room, at the single new 'rack_shelf' level.
#   3. The now-childless Site/Floor rows are deleted (Floors first, since
#      Sites still reference them via the PROTECT'd parent FK until they're
#      gone).
# `path` is recomputed by hand for every re-parented row to match exactly
# what the INSERT trigger would have produced — the trigger only fires
# BEFORE INSERT, never on UPDATE (see 0002's own docstring), so a plain
# re-parenting UPDATE would otherwise leave a stale path behind.

from django.db import migrations, models

REPARENT_ROOMS_UNDER_COUNTRY_SQL = """
UPDATE locations_location AS room
SET parent_id = country.id,
    path = country.path || text2ltree(replace(room.id::text, '-', ''))
FROM locations_location AS country
WHERE room.level = 'storage_room'
  AND country.level = 'country'
  AND country.path = subpath(room.path, 0, 1)
  AND EXISTS (
      SELECT 1 FROM locations_location AS old_parent
      WHERE old_parent.id = room.parent_id AND old_parent.level IN ('site', 'floor')
  );
"""

FLATTEN_RACKS_AND_SHELVES_SQL = """
UPDATE locations_location AS node
SET parent_id = room.id,
    level = 'rack_shelf',
    path = room.path || text2ltree(replace(node.id::text, '-', ''))
FROM locations_location AS room
WHERE node.level IN ('rack_cabinet', 'shelf_bin')
  AND room.level = 'storage_room'
  AND (
      -- A Rack/Cabinet directly under the room, or a Shelf/Bin the (old,
      -- six-level) schema already allowed to sit directly under a room.
      node.parent_id = room.id
      -- A Shelf/Bin nested one level deeper, under a Rack/Cabinet that's
      -- under the room — parent_id chains are still fully intact here
      -- (only ever mutated by this same statement), unlike `path`, which
      -- the room reparenting above already rewrote — a path-prefix match
      -- against the room's now-final path would silently match nothing,
      -- since every rack/shelf's own `path` is still the stale, pre-
      -- reparent value at this point in the migration.
      OR node.parent_id IN (
          SELECT id FROM locations_location
          WHERE parent_id = room.id AND level = 'rack_cabinet'
      )
  );
"""

# A UserLocationAccess grant is allowed at any level, including a bare
# Site/Floor (docs/architecture's multi-country grant support) — those rows
# must move before the Site/Floor rows they point at can be deleted below.
# Re-pointed to the Country ancestor rather than dropped: a grant that used
# to cascade to everything under that Site/Floor must keep covering at
# least that much, and Country-level grants are already a normal, supported
# shape in this app. Where the same user already holds a separate grant at
# that Country (the UNIQUE(user, location) constraint would collide), the
# now-redundant Site/Floor grant is simply dropped instead of re-pointed —
# the user already has that access via the other row.
REPOINT_LOCATION_GRANTS_TO_COUNTRY_SQL = """
UPDATE accounts_userlocationaccess AS access_grant
SET location_id = country.id
FROM locations_location AS site_or_floor
JOIN locations_location AS country
    ON country.level = 'country' AND country.path = subpath(site_or_floor.path, 0, 1)
WHERE access_grant.location_id = site_or_floor.id
  AND site_or_floor.level IN ('site', 'floor')
  AND NOT EXISTS (
      SELECT 1 FROM accounts_userlocationaccess existing
      WHERE existing.user_id = access_grant.user_id AND existing.location_id = country.id
  );
"""

DROP_REDUNDANT_LOCATION_GRANTS_SQL = """
DELETE FROM accounts_userlocationaccess AS access_grant
USING locations_location AS site_or_floor
WHERE access_grant.location_id = site_or_floor.id AND site_or_floor.level IN ('site', 'floor');
"""

# A Site/Floor can still be directly referenced by a historical ledger row
# (e.g. an old InventoryTransaction.destination_location recorded before
# this app enforced require_room_or_below() on every write) even after
# every Location.parent reference to it is gone. Ledger tables are
# append-only — CLAUDE.md's working agreement, and services/ledger.py's own
# invariant — so that row can never be edited or re-pointed to make room
# for this delete; the only safe move is to leave that one Location exactly
# as it is, orphaned outside the new three-level tree but still resolvable
# for whatever historical record needs it. A plain bulk DELETE has no
# "skip the ones that fail" mode, and enumerating every FK that might
# reference a Location by hand is exactly how the first version of this
# migration missed one (destination_location) — this loops row by row and
# catches the constraint violation per row instead, so it's correct
# regardless of which table (or a future one) holds the reference.
#
# SET CONSTRAINTS ALL IMMEDIATE is not optional: this app's ledger FKs are
# DEFERRABLE INITIALLY DEFERRED, so a violation is normally only raised at
# transaction COMMIT — by which point the DO block below has long since
# returned and its EXCEPTION handler can no longer catch anything.
# Confirmed live against a reconstructed copy of exactly this scenario
# (a Location manually inserted at 'floor' level with an
# InventoryTransaction.destination_location pointing at it, trigger
# temporarily disabled to allow the otherwise-now-invalid insert): without
# this line the DO block "succeeds" but the enclosing migration transaction
# still fails at commit with the same FK violation; with it, the violation
# surfaces synchronously inside the DELETE and is caught per-row as
# intended, leaving that one row in place and the ledger row it's
# referenced from completely untouched.
DELETE_UNREFERENCED_FLOORS_AND_SITES_SQL = """
SET CONSTRAINTS ALL IMMEDIATE;

DO $$
DECLARE
    loc RECORD;
BEGIN
    FOR loc IN SELECT id FROM locations_location WHERE level = 'floor' LOOP
        BEGIN
            DELETE FROM locations_location WHERE id = loc.id;
        EXCEPTION WHEN foreign_key_violation THEN
            RAISE NOTICE 'Leaving floor location % in place — still referenced '
                'elsewhere (likely historical ledger data)', loc.id;
        END;
    END LOOP;
    FOR loc IN SELECT id FROM locations_location WHERE level = 'site' LOOP
        BEGIN
            DELETE FROM locations_location WHERE id = loc.id;
        EXCEPTION WHEN foreign_key_violation THEN
            RAISE NOTICE 'Leaving site location % in place — still referenced '
                'elsewhere (likely historical ledger data)', loc.id;
        END;
    END LOOP;
END $$;
"""

NEW_SET_PATH_FUNCTION_SQL = """
CREATE OR REPLACE FUNCTION locations_location_set_path() RETURNS trigger AS $$
DECLARE
    parent_path ltree;
    parent_level varchar;
    expected_child_level varchar;
BEGIN
    IF NEW.parent_id IS NULL THEN
        IF NEW.level <> 'country' THEN
            RAISE EXCEPTION 'Only a country-level location may have no parent';
        END IF;
        NEW.path := text2ltree(replace(NEW.id::text, '-', ''));
    ELSE
        SELECT path, level INTO parent_path, parent_level
        FROM locations_location WHERE id = NEW.parent_id;

        IF parent_path IS NULL THEN
            RAISE EXCEPTION 'Parent location % does not exist', NEW.parent_id;
        END IF;

        expected_child_level := CASE parent_level
            WHEN 'country' THEN 'storage_room'
            WHEN 'storage_room' THEN 'rack_shelf'
            ELSE NULL
        END;

        IF expected_child_level IS NULL OR NEW.level <> expected_child_level THEN
            RAISE EXCEPTION 'A % may only be created under a %, but parent % is a %',
                NEW.level, expected_child_level, NEW.parent_id, parent_level;
        END IF;

        NEW.path := parent_path || text2ltree(replace(NEW.id::text, '-', ''));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

OLD_SET_PATH_FUNCTION_SQL = """
CREATE OR REPLACE FUNCTION locations_location_set_path() RETURNS trigger AS $$
DECLARE
    parent_path ltree;
    parent_level varchar;
    expected_child_level varchar;
BEGIN
    IF NEW.parent_id IS NULL THEN
        IF NEW.level <> 'country' THEN
            RAISE EXCEPTION 'Only a country-level location may have no parent';
        END IF;
        NEW.path := text2ltree(replace(NEW.id::text, '-', ''));
    ELSE
        SELECT path, level INTO parent_path, parent_level
        FROM locations_location WHERE id = NEW.parent_id;

        IF parent_path IS NULL THEN
            RAISE EXCEPTION 'Parent location % does not exist', NEW.parent_id;
        END IF;

        expected_child_level := CASE parent_level
            WHEN 'country' THEN 'site'
            WHEN 'site' THEN 'floor'
            WHEN 'floor' THEN 'storage_room'
            WHEN 'storage_room' THEN 'rack_cabinet'
            WHEN 'rack_cabinet' THEN 'shelf_bin'
            ELSE NULL
        END;

        IF expected_child_level IS NULL OR NEW.level <> expected_child_level THEN
            RAISE EXCEPTION 'A % may only be created under a %, but parent % is a %',
                NEW.level, expected_child_level, NEW.parent_id, parent_level;
        END IF;

        NEW.path := parent_path || text2ltree(replace(NEW.id::text, '-', ''));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_location_path_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="level",
            field=models.CharField(
                choices=[
                    ("country", "Country"),
                    ("storage_room", "Storage Room"),
                    ("rack_shelf", "Rack/Shelf"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunSQL(sql=REPARENT_ROOMS_UNDER_COUNTRY_SQL, reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql=FLATTEN_RACKS_AND_SHELVES_SQL, reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(
            sql=REPOINT_LOCATION_GRANTS_TO_COUNTRY_SQL, reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql=DROP_REDUNDANT_LOCATION_GRANTS_SQL, reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql=DELETE_UNREFERENCED_FLOORS_AND_SITES_SQL, reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(sql=NEW_SET_PATH_FUNCTION_SQL, reverse_sql=OLD_SET_PATH_FUNCTION_SQL),
    ]
