# Generated by Django 5.2.17 on 2026-08-25 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("export_path", models.CharField(blank=True, max_length=500)),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("disabled", "Disabled"),
                            ("nightly", "Nightly"),
                            ("weekly", "Weekly"),
                        ],
                        default="disabled",
                        max_length=10,
                    ),
                ),
                (
                    "weekly_weekday",
                    models.PositiveSmallIntegerField(
                        default=6,
                        help_text="0=Monday .. 6=Sunday (Python's date.weekday()); only used when schedule=weekly.",
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_run_status",
                    models.CharField(
                        blank=True,
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=10,
                    ),
                ),
                ("last_run_detail", models.TextField(blank=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "export settings",
                "verbose_name_plural": "export settings",
            },
        ),
    ]
