# Generated by Django 5.2.17 on 2026-08-24 14:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("locations", "0002_location_path_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("receipt", "Receipt into stock"),
                            ("transfer", "Location transfer"),
                            ("reservation", "Reservation"),
                            ("reservation_release", "Reservation release"),
                            ("assignment", "Employee assignment"),
                            ("delivery", "Customer delivery"),
                            ("return", "Return"),
                            ("return_assessment", "Return assessment"),
                            ("mark_damaged", "Mark damaged"),
                            ("mark_lost", "Mark lost"),
                            ("disposal", "Disposal"),
                            ("correction", "Administrator correction"),
                            ("reversal", "Reversal"),
                        ],
                        max_length=25,
                    ),
                ),
                ("occurred_at", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("project_reference", models.CharField(blank=True, max_length=120)),
                ("final_customer", models.CharField(blank=True, max_length=120)),
                ("employee_name", models.CharField(blank=True, max_length=120)),
                ("is_temporary_assignment", models.BooleanField(blank=True, null=True)),
                ("expected_return_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("duplicate_serial_acknowledged", models.BooleanField(default=False)),
                (
                    "destination_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_to",
                        to="locations.location",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performed_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="related_transactions",
                        to="inventory.inventorytransaction",
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_from",
                        to="locations.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("on_hand_quantity", models.IntegerField(default=0)),
                ("reserved_quantity", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_balances",
                        to="locations.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_balances",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnitAsset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("vendor_serial", models.CharField(blank=True, max_length=120)),
                ("normalized_serial", models.CharField(blank=True, editable=False, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("reserved", "Reserved"),
                            ("assigned", "Assigned"),
                            ("delivered", "Delivered"),
                            ("returned", "Returned"),
                            ("damaged", "Damaged"),
                            ("lost", "Lost"),
                            ("disposed", "Disposed"),
                        ],
                        default="in_stock",
                        max_length=20,
                    ),
                ),
                ("project_reference", models.CharField(blank=True, max_length=120)),
                ("final_customer", models.CharField(blank=True, max_length=120)),
                ("supplier", models.CharField(blank=True, max_length=120)),
                ("invoice_number", models.CharField(blank=True, max_length=60)),
                ("arrival_date", models.DateField()),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("damaged", "Damaged"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("accessories", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("last_removal_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unit_assets",
                        to="locations.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unit_assets",
                        to="catalog.product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryTransactionLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("line_number", models.PositiveIntegerField()),
                ("quantity_delta", models.IntegerField()),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in_stock", "In Stock"),
                            ("reserved", "Reserved"),
                            ("assigned", "Assigned"),
                            ("delivered", "Delivered"),
                            ("returned", "Returned"),
                            ("damaged", "Damaged"),
                            ("lost", "Lost"),
                            ("disposed", "Disposed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in_stock", "In Stock"),
                            ("reserved", "Reserved"),
                            ("assigned", "Assigned"),
                            ("delivered", "Delivered"),
                            ("returned", "Returned"),
                            ("damaged", "Damaged"),
                            ("lost", "Lost"),
                            ("disposed", "Disposed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("brand_snapshot", models.CharField(blank=True, max_length=120)),
                ("model_snapshot", models.CharField(blank=True, max_length=120)),
                ("sku_snapshot", models.CharField(blank=True, max_length=60)),
                ("type_snapshot", models.CharField(blank=True, max_length=80)),
                ("description_snapshot", models.TextField(blank=True)),
                ("serial_snapshot", models.CharField(blank=True, max_length=120)),
                ("project_reference_snapshot", models.CharField(blank=True, max_length=120)),
                ("final_customer_snapshot", models.CharField(blank=True, max_length=120)),
                ("supplier_snapshot", models.CharField(blank=True, max_length=120)),
                ("invoice_number_snapshot", models.CharField(blank=True, max_length=60)),
                ("condition_snapshot", models.CharField(blank=True, max_length=20)),
                ("accessories_snapshot", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction_lines",
                        to="catalog.product",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="inventory.inventorytransaction",
                    ),
                ),
                (
                    "unit_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction_lines",
                        to="inventory.unitasset",
                    ),
                ),
            ],
            options={
                "ordering": ["transaction", "line_number"],
            },
        ),
        migrations.CreateModel(
            name="AssetStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in_stock", "In Stock"),
                            ("reserved", "Reserved"),
                            ("assigned", "Assigned"),
                            ("delivered", "Delivered"),
                            ("returned", "Returned"),
                            ("damaged", "Damaged"),
                            ("lost", "Lost"),
                            ("disposed", "Disposed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("reserved", "Reserved"),
                            ("assigned", "Assigned"),
                            ("delivered", "Delivered"),
                            ("returned", "Returned"),
                            ("damaged", "Damaged"),
                            ("lost", "Lost"),
                            ("disposed", "Disposed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_status_events",
                        to="inventory.inventorytransaction",
                    ),
                ),
                (
                    "unit_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="inventory.unitasset",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "asset status history",
                "ordering": ["occurred_at"],
            },
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["movement_type"], name="txn_movement_type_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["performed_by"], name="txn_performed_by_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["occurred_at"], name="txn_occurred_at_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["source_location"], name="txn_source_location_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["destination_location"], name="txn_destination_location_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["project_reference"], name="txn_project_ref_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["final_customer"], name="txn_final_customer_idx"),
        ),
        migrations.AddConstraint(
            model_name="inventorytransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "movement_type__in",
                        [
                            "receipt",
                            "transfer",
                            "reservation",
                            "reservation_release",
                            "assignment",
                            "delivery",
                            "return",
                            "return_assessment",
                            "mark_damaged",
                            "mark_lost",
                            "disposal",
                            "correction",
                            "reversal",
                        ],
                    )
                ),
                name="txn_movement_type_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="stockbalance",
            index=models.Index(fields=["location"], name="stockbalance_location_idx"),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.UniqueConstraint(
                fields=("product", "location"), name="stockbalance_unique_product_location"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("on_hand_quantity__gte", 0)),
                name="stockbalance_on_hand_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_quantity__gte", 0)),
                name="stockbalance_reserved_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_quantity__lte", models.F("on_hand_quantity"))),
                name="stockbalance_reserved_lte_on_hand",
            ),
        ),
        migrations.AddIndex(
            model_name="unitasset",
            index=models.Index(fields=["normalized_serial"], name="unitasset_serial_idx"),
        ),
        migrations.AddIndex(
            model_name="unitasset",
            index=models.Index(fields=["product", "status"], name="unitasset_product_status_idx"),
        ),
        migrations.AddIndex(
            model_name="unitasset",
            index=models.Index(fields=["status"], name="unitasset_status_idx"),
        ),
        migrations.AddIndex(
            model_name="unitasset",
            index=models.Index(fields=["current_location"], name="unitasset_location_idx"),
        ),
        migrations.AddIndex(
            model_name="unitasset",
            index=models.Index(fields=["project_reference"], name="unitasset_project_ref_idx"),
        ),
        migrations.AddIndex(
            model_name="unitasset",
            index=models.Index(fields=["final_customer"], name="unitasset_final_customer_idx"),
        ),
        migrations.AddIndex(
            model_name="unitasset",
            index=models.Index(fields=["arrival_date"], name="unitasset_arrival_date_idx"),
        ),
        migrations.AddIndex(
            model_name="unitasset",
            index=models.Index(fields=["last_removal_date"], name="unitasset_removal_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="unitasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "in_stock",
                            "reserved",
                            "assigned",
                            "delivered",
                            "returned",
                            "damaged",
                            "lost",
                            "disposed",
                        ],
                    )
                ),
                name="unitasset_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransactionline",
            index=models.Index(fields=["transaction"], name="txnline_transaction_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorytransactionline",
            index=models.Index(fields=["unit_asset"], name="txnline_unit_asset_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorytransactionline",
            index=models.Index(fields=["product"], name="txnline_product_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorytransactionline",
            index=models.Index(
                fields=["project_reference_snapshot"], name="txnline_project_ref_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransactionline",
            index=models.Index(
                fields=["final_customer_snapshot"], name="txnline_final_customer_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorytransactionline",
            constraint=models.UniqueConstraint(
                fields=("transaction", "line_number"), name="txnline_unique_line_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorytransactionline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("unit_asset__isnull", False), ("quantity_delta__in", [-1, 1])),
                    models.Q(
                        ("unit_asset__isnull", True), models.Q(("quantity_delta", 0), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="txnline_quantity_delta_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="assetstatushistory",
            index=models.Index(fields=["unit_asset"], name="assetstatus_unit_asset_idx"),
        ),
    ]
