# Generated by Django 5.2.17 on 2026-09-02 18:53

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_brand_brand_name_trgm_idx_and_more"),
        ("inventory", "0004_reservation_ledger_integrity"),
        ("locations", "0002_location_path_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="unitasset",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["normalized_serial"],
                name="unitasset_serial_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="unitasset",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["project_reference"],
                name="unitasset_project_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="unitasset",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["final_customer"],
                name="unitasset_customer_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
