# Generated by Django 5.2.17 on 2026-09-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_savedgridview"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytransaction",
            name="wipe_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("software_wipe", "Software data wipe"),
                    ("degaussed", "Degaussed"),
                    ("physically_destroyed", "Physically destroyed"),
                    ("not_applicable", "No storage media"),
                ],
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="witness_name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
