# Generated by Django 5.2.17 on 2026-09-04 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_brand_brand_name_trgm_idx_and_more"),
        ("inventory", "0007_inventorytransaction_wipe_method_and_more"),
        ("locations", "0002_location_path_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inventorytransaction",
            name="txn_movement_type_valid",
        ),
        migrations.RemoveConstraint(
            model_name="stockbalance",
            name="stockbalance_unique_product_location",
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="recipient_reference",
            field=models.CharField(
                blank=True,
                help_text="Optional employee or customer reference/ID, entered manually — not a lookup against any master data (spec §22 excludes customer/contact master data).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="inventorytransactionline",
            name="stock_purpose_snapshot",
            field=models.CharField(
                choices=[("internal", "Internal"), ("customer", "Customer")],
                default="internal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stockbalance",
            name="stock_purpose",
            field=models.CharField(
                choices=[("internal", "Internal"), ("customer", "Customer")],
                default="internal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="stock_purpose",
            field=models.CharField(
                choices=[("internal", "Internal"), ("customer", "Customer")],
                default="internal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="unitasset",
            name="current_custody_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="The assignment/delivery transaction that currently holds this asset outside storage — cleared on return. Every other 'Assigned To' display field (recipient, project reference, date, expected return) is read from this transaction rather than duplicated onto UnitAsset.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="custodied_assets",
                to="inventory.inventorytransaction",
            ),
        ),
        migrations.AddField(
            model_name="unitasset",
            name="stock_purpose",
            field=models.CharField(
                choices=[("internal", "Internal"), ("customer", "Customer")],
                default="internal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("receipt", "Receipt into stock"),
                    ("transfer", "Location transfer"),
                    ("reservation", "Reservation"),
                    ("reservation_release", "Reservation release"),
                    ("assignment", "Employee assignment"),
                    ("delivery", "Customer delivery"),
                    ("return", "Return"),
                    ("return_assessment", "Return assessment"),
                    ("mark_damaged", "Mark damaged"),
                    ("mark_lost", "Mark lost"),
                    ("disposal", "Disposal"),
                    ("correction", "Administrator correction"),
                    ("reversal", "Reversal"),
                    ("purpose_change", "Stock purpose reclassification"),
                ],
                max_length=25,
            ),
        ),
        migrations.AddIndex(
            model_name="unitasset",
            index=models.Index(fields=["stock_purpose"], name="unitasset_stock_purpose_idx"),
        ),
        migrations.AddConstraint(
            model_name="inventorytransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "movement_type__in",
                        [
                            "receipt",
                            "transfer",
                            "reservation",
                            "reservation_release",
                            "assignment",
                            "delivery",
                            "return",
                            "return_assessment",
                            "mark_damaged",
                            "mark_lost",
                            "disposal",
                            "correction",
                            "reversal",
                            "purpose_change",
                        ],
                    )
                ),
                name="txn_movement_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.UniqueConstraint(
                fields=("product", "location", "stock_purpose"),
                name="stockbalance_unique_product_location_purpose",
            ),
        ),
    ]
