# Generated by Django 5.2.17 on 2026-09-04 09:27

from django.db import migrations, models


def remap_retired_condition_values(apps, schema_editor):
    """Good/Fair/Unknown -> Used — the retired values collapse into the new
    set's closest neutral catch-all. New/Damaged are unaffected. Ledger
    condition_snapshot values are historical fact and are deliberately left
    untouched (docs/architecture/06-documents-and-snapshots.md).
    """
    UnitAsset = apps.get_model("inventory", "UnitAsset")
    UnitAsset.objects.filter(condition__in=["good", "fair", "unknown"]).update(condition="used")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_remove_inventorytransaction_txn_movement_type_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitasset",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("refurbished", "Refurbished"),
                    ("used", "Used"),
                    ("damaged", "Damaged"),
                ],
                default="used",
                max_length=20,
            ),
        ),
        migrations.RunPython(remap_retired_condition_values, noop_reverse),
    ]
