# Generated by Django 5.2.17 on 2026-09-04 12:38

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_unitasset_condition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("reference", models.CharField(blank=True, max_length=60)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional live reference to a Customer row, resolved via search/autofill (apps.inventory.views.CustomerSearchDataView). final_customer stays the historical name snapshot regardless of whether this is set.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="inventory.customer",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="customer_name_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference", ""), _negated=True),
                fields=("reference",),
                name="customer_unique_reference_when_set",
            ),
        ),
    ]
