# Generated by Django 5.2.17 on 2026-09-04 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_backfill_customers_from_final_customer"),
        ("locations", "0002_location_path_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inventorytransaction",
            name="txn_movement_type_valid",
        ),
        migrations.AddField(
            model_name="unitasset",
            name="installed_in",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent asset this Component-category item is currently installed in, if any — set/cleared only by apps.inventory.services.components.install_component()/remove_component(), never a plain field edit. Applies to Component-category items only; always null for every other category.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="installed_components",
                to="inventory.unitasset",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("receipt", "Receipt into stock"),
                    ("transfer", "Location transfer"),
                    ("reservation", "Reservation"),
                    ("reservation_release", "Reservation release"),
                    ("assignment", "Employee assignment"),
                    ("delivery", "Customer delivery"),
                    ("return", "Return"),
                    ("return_assessment", "Return assessment"),
                    ("mark_damaged", "Mark damaged"),
                    ("mark_lost", "Mark lost"),
                    ("disposal", "Disposal"),
                    ("correction", "Administrator correction"),
                    ("reversal", "Reversal"),
                    ("purpose_change", "Stock purpose reclassification"),
                    ("install_component", "Install component"),
                    ("remove_component", "Remove component"),
                ],
                max_length=25,
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorytransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "movement_type__in",
                        [
                            "receipt",
                            "transfer",
                            "reservation",
                            "reservation_release",
                            "assignment",
                            "delivery",
                            "return",
                            "return_assessment",
                            "mark_damaged",
                            "mark_lost",
                            "disposal",
                            "correction",
                            "reversal",
                            "purpose_change",
                            "install_component",
                            "remove_component",
                        ],
                    )
                ),
                name="txn_movement_type_valid",
            ),
        ),
    ]
