# Generated by Django 5.2.17 on 2026-09-05 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_remove_inventorytransaction_txn_movement_type_valid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="savedgridview",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Applied automatically when this grid loads, instead of the grid's own built-in defaults. At most one default per (user, grid).",
            ),
        ),
        migrations.AlterField(
            model_name="savedgridview",
            name="grid_key",
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name="savedgridview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("created_by", "grid_key"),
                name="savedgridview_one_default_per_user_per_grid",
            ),
        ),
    ]
