# Generated by Django 5.2.17 on 2026-09-05 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_min_reorder_quantity_and_more"),
        ("inventory", "0013_savedgridview_is_default_and_more"),
        ("locations", "0002_location_path_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductLocationThreshold",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("target_stock_level", models.PositiveIntegerField(blank=True, null=True)),
                ("min_reorder_quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("preferred_supplier", models.CharField(blank=True, max_length=120)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_thresholds",
                        to="catalog.product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["product__brand__name", "product__model", "location__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "location"), name="productlocationthreshold_unique"
                    )
                ],
            },
        ),
    ]
