# Generated by Django 5.2.17 on 2026-09-05 23:10, hand-edited to use
# CONCURRENTLY for every index operation — these tables (UnitAsset,
# InventoryTransaction, InventoryTransactionLine) are append-only/high-write
# ledger tables that must never be locked for the duration of an index
# build/drop in production.

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently, RemoveIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # CONCURRENTLY cannot run inside a transaction.
    atomic = False

    dependencies = [
        ("catalog", "0008_remove_product_product_brand_idx_and_more"),
        ("inventory", "0014_productlocationthreshold"),
        ("locations", "0002_location_path_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name="assetstatushistory",
            name="assetstatus_unit_asset_idx",
        ),
        RemoveIndexConcurrently(
            model_name="inventorytransaction",
            name="txn_performed_by_idx",
        ),
        RemoveIndexConcurrently(
            model_name="inventorytransaction",
            name="txn_occurred_at_idx",
        ),
        RemoveIndexConcurrently(
            model_name="inventorytransaction",
            name="txn_source_location_idx",
        ),
        RemoveIndexConcurrently(
            model_name="inventorytransaction",
            name="txn_destination_location_idx",
        ),
        RemoveIndexConcurrently(
            model_name="inventorytransactionline",
            name="txnline_transaction_idx",
        ),
        RemoveIndexConcurrently(
            model_name="inventorytransactionline",
            name="txnline_unit_asset_idx",
        ),
        RemoveIndexConcurrently(
            model_name="inventorytransactionline",
            name="txnline_product_idx",
        ),
        RemoveIndexConcurrently(
            model_name="stockbalance",
            name="stockbalance_location_idx",
        ),
        RemoveIndexConcurrently(
            model_name="unitasset",
            name="unitasset_location_idx",
        ),
        AddIndexConcurrently(
            model_name="assetstatushistory",
            index=models.Index(fields=["occurred_at"], name="assetstatus_occurred_at_idx"),
        ),
        AddIndexConcurrently(
            model_name="assetstatushistory",
            index=models.Index(
                fields=["unit_asset", "occurred_at"], name="assetstatus_asset_occ_idx"
            ),
        ),
        AddIndexConcurrently(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["occurred_at", "created_at"], name="txn_occurred_created_idx"
            ),
        ),
        AddIndexConcurrently(
            model_name="stockreservation",
            index=models.Index(fields=["created_at"], name="reservation_created_at_idx"),
        ),
        AddIndexConcurrently(
            model_name="unitasset",
            index=models.Index(fields=["created_at"], name="unitasset_created_at_idx"),
        ),
    ]
