# Generated by Django 5.2.17 on 2026-09-05 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_remove_assetstatushistory_assetstatus_unit_asset_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetstatushistory",
            name="unit_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="status_history",
                to="inventory.unitasset",
            ),
        ),
    ]
