# Generated by Django 5.2.17 on 2026-09-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_alter_assetstatushistory_unit_asset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorytransaction",
            name="wipe_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("software_wipe", "Software data wipe"),
                    ("degaussed", "Degaussed"),
                    ("physically_destroyed", "Physically destroyed"),
                    ("not_applicable", "Not applicable — no storage media"),
                ],
                max_length=25,
            ),
        ),
    ]
