# Generated by Django 5.2.17 on 2026-09-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_gridselection"),
    ]

    operations = [
        migrations.AddField(
            model_name="productlocationthreshold",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
