# Generated by Django 5.2.17 on 2026-08-25 13:54

import apps.settings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site_name",
                    models.CharField(blank=True, default="Stock Inventory", max_length=100),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True, null=True, upload_to=apps.settings.models._logo_upload_path
                    ),
                ),
                (
                    "allowed_hosts_override",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated hostnames. Leave blank to keep the ALLOWED_HOSTS value from .env.production (wildcarded by default). Setting this REPLACES that value for every request going forward — a wrong value here can lock you out of the site; see docs/architecture/09-delivery-backlog.md's Settings section for the recovery command if that happens.",
                        max_length=1000,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "system settings",
                "verbose_name_plural": "system settings",
            },
        ),
    ]
