# Generated by Django 5.2.17 on 2026-09-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sysconfig", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="accent_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hex color (e.g. #2563eb) used for primary buttons, links, and focus rings app-wide. Leave blank for the built-in default blue.",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_from_email",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_host",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_password",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_port",
            field=models.PositiveIntegerField(blank=True, default=587, null=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_use_tls",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_username",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text='IANA zone name (e.g. "America/New_York"). Leave blank to use the server\'s configured default (currently the TIME_ZONE environment variable).',
                max_length=63,
            ),
        ),
    ]
