# Generated by Django 5.2.17 on 2026-09-05 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_location_path_trigger"),
        ("sysconfig", "0002_systemsettings_accent_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSubscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notify_low_stock", models.BooleanField(default=True)),
                ("notify_overdue_assignments", models.BooleanField(default=True)),
                ("notify_import_export_failures", models.BooleanField(default=True)),
                ("notify_data_quality", models.BooleanField(default=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_subscriptions",
                        to="locations.location",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_notification_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["country__name", "recipient__username"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDigestDelivery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("digest_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("no_content", "No content"),
                            ("failed", "Failed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("item_counts", models.JSONField(blank=True, default=dict)),
                ("detail", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="sysconfig.notificationsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-digest_date", "subscription__country__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="notificationsubscription",
            constraint=models.UniqueConstraint(
                fields=("recipient", "country"), name="notification_unique_recipient_country"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdigestdelivery",
            constraint=models.UniqueConstraint(
                fields=("subscription", "digest_date"),
                name="notification_unique_subscription_digest_date",
            ),
        ),
    ]
