# Generated by Django 5.2.17 on 2026-09-06 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_location_path_trigger"),
        ("sysconfig", "0003_notificationsubscription_notificationdigestdelivery_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low stock"),
                            ("overdue_assignments", "Overdue temporary assignments"),
                            ("import_export_failures", "Import/export failures"),
                            ("high_data_quality", "Data quality"),
                        ],
                        max_length=30,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("url", models.CharField(blank=True, max_length=255)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="sysconfig.notificationdigestdelivery",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["recipient", "read_at"], name="notif_recipient_read_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("delivery", "category"),
                        name="unique_notification_per_delivery_category",
                    )
                ],
            },
        ),
    ]
