# Generated by Django 5.2.17 on 2026-09-07 18:51

from django.db import migrations, models


def rename_untouched_default(apps, schema_editor):
    """Only the singleton row that's still on the old default gets renamed —
    an Administrator who already picked their own custom site_name keeps it,
    per this app's "preserve existing user changes" convention.
    """
    SystemSettings = apps.get_model("sysconfig", "SystemSettings")
    SystemSettings.objects.filter(site_name="Stock Inventory").update(site_name="Invenio")


class Migration(migrations.Migration):

    dependencies = [
        ("sysconfig", "0004_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="site_name",
            field=models.CharField(blank=True, default="Invenio", max_length=100),
        ),
        migrations.RunPython(rename_untouched_default, migrations.RunPython.noop),
    ]
