# Generated by Django 5.2.17 on 2026-08-24 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Login success"),
                            ("login_failure", "Login failure"),
                            ("record_created", "Record created"),
                            ("record_updated", "Record updated"),
                            ("movement_completed", "Movement completed"),
                            ("duplicate_serial_acknowledged", "Duplicate serial acknowledged"),
                            ("duplicate_product_acknowledged", "Duplicate product acknowledged"),
                            ("document_generated", "Document generated"),
                            ("attachment_uploaded", "Attachment uploaded"),
                            ("attachment_deleted", "Attachment deleted"),
                            ("import_executed", "Import executed"),
                            ("export_executed", "Export executed"),
                            ("permission_changed", "Permission changed"),
                            ("admin_correction", "Administrator correction"),
                            ("admin_reversal", "Administrator reversal"),
                        ],
                        max_length=40,
                    ),
                ),
                ("object_type", models.CharField(blank=True, max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("summary", models.TextField(blank=True)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(fields=["object_type", "object_id"], name="audit_object_idx"),
                    models.Index(fields=["actor"], name="audit_actor_idx"),
                    models.Index(fields=["event_type"], name="audit_event_type_idx"),
                    models.Index(fields=["occurred_at"], name="audit_occurred_at_idx"),
                ],
            },
        ),
    ]
