# Generated by Django 5.2.17 on 2026-09-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_alter_auditevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login_success", "Login success"),
                    ("login_failure", "Login failure"),
                    ("record_created", "Record created"),
                    ("record_updated", "Record updated"),
                    ("movement_completed", "Movement completed"),
                    ("duplicate_serial_acknowledged", "Duplicate serial acknowledged"),
                    ("duplicate_product_acknowledged", "Duplicate product acknowledged"),
                    ("document_generated", "Document generated"),
                    ("attachment_uploaded", "Attachment uploaded"),
                    ("attachment_deleted", "Attachment deleted"),
                    ("import_executed", "Import executed"),
                    ("export_executed", "Export executed"),
                    ("permission_changed", "Permission changed"),
                    ("admin_correction", "Administrator correction"),
                    ("admin_reversal", "Administrator reversal"),
                    ("stock_purpose_changed", "Stock purpose changed"),
                    ("component_association_changed", "Component association changed"),
                    ("data_quality_finding_resolved", "Data quality finding resolved"),
                ],
                max_length=40,
            ),
        ),
    ]
