# Generated by Django 5.2.17 on 2026-09-05 23:10, hand-edited to use
# CONCURRENTLY — AuditEvent is append-only and grows forever.

from django.contrib.postgres.operations import RemoveIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("audit", "0004_alter_auditevent_event_type"),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name="auditevent",
            name="audit_actor_idx",
        ),
    ]
