# Generated by Django 5.2.17 on 2026-08-24 14:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "product type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("model", models.CharField(max_length=120)),
                ("sku", models.CharField(blank=True, max_length=60)),
                ("normalized_model", models.CharField(blank=True, editable=False, max_length=120)),
                ("normalized_sku", models.CharField(blank=True, editable=False, max_length=60)),
                ("description", models.TextField(blank=True)),
                (
                    "tracking_method",
                    models.CharField(
                        choices=[("unit", "Unit (serialized)"), ("quantity", "Quantity")],
                        max_length=10,
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=120)),
                ("default_notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("low_stock_threshold", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.brand",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.producttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["normalized_model", "normalized_sku"], name="product_normalized_idx"
                    ),
                    models.Index(fields=["brand"], name="product_brand_idx"),
                    models.Index(fields=["product_type"], name="product_type_idx"),
                    models.Index(fields=["is_active"], name="product_active_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("tracking_method", "unit"), _negated=True),
                            ("low_stock_threshold__isnull", True),
                            _connector="OR",
                        ),
                        name="product_low_stock_threshold_unit_null",
                    )
                ],
            },
        ),
    ]
