# Generated by Django 5.2.17 on 2026-09-02 18:53

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_productcustomfielddefinition_and_more"),
        # pg_trgm must exist before a gin_trgm_ops index can be created.
        ("core", "0002_enable_pg_trgm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="brand",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="brand_name_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["model"], name="product_model_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["sku"], name="product_sku_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
