# Generated by Django 5.2.17 on 2026-09-04 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_brand_brand_name_trgm_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("serialized_asset", "Serialized Asset"),
                    ("quantity_stock", "Quantity Stock"),
                    ("consumable", "Consumable"),
                    ("reusable_accessory", "Reusable Accessory"),
                    ("component", "Component"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("category__isnull", True),
                    models.Q(
                        ("category__in", ["serialized_asset", "reusable_accessory", "component"]),
                        ("tracking_method", "unit"),
                    ),
                    models.Q(
                        ("category__in", ["quantity_stock", "consumable"]),
                        ("tracking_method", "quantity"),
                    ),
                    _connector="OR",
                ),
                name="product_category_tracking_method_agree",
            ),
        ),
    ]
