# Generated by Django 5.2.17 on 2026-09-05 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_require_item_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="min_reorder_quantity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Never suggest reordering fewer than this many units.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="preferred_supplier",
            field=models.CharField(
                blank=True, help_text="Shown on the reorder suggestions report.", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="target_stock_level",
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Reorder up to this many units. Leave blank to show "Configuration required" on the reorder suggestions report instead of a suggested quantity.',
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("tracking_method", "unit"), _negated=True),
                    models.Q(
                        ("target_stock_level__isnull", True), ("min_reorder_quantity__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="product_reorder_fields_unit_null",
            ),
        ),
    ]
