# Generated by Django 5.2.17 on 2026-09-05 23:10, hand-edited to use
# CONCURRENTLY — Product is read on nearly every page in this app.

from django.contrib.postgres.operations import RemoveIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("catalog", "0007_product_min_reorder_quantity_and_more"),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name="product",
            name="product_brand_idx",
        ),
        RemoveIndexConcurrently(
            model_name="product",
            name="product_type_idx",
        ),
    ]
