# Generated by Django 5.2.17 on 2026-09-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_product_category"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="product_low_stock_threshold_unit_null",
        ),
        migrations.RemoveConstraint(
            model_name="product",
            name="product_reorder_fields_unit_null",
        ),
    ]
