# Generated by Django 5.2.17 on 2026-09-04 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0002_duplicate_serial_acknowledgement"),
        ("locations", "0002_location_path_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="default_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="default_stock_purpose",
            field=models.CharField(
                choices=[("internal", "Internal"), ("customer", "Customer")],
                default="internal",
                max_length=20,
            ),
        ),
    ]
