# Generated by Django 5.2.17 on 2026-09-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0003_importbatch_default_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("previewed", "Previewed"),
                    ("executing", "Executing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("partially_completed", "Partially completed"),
                ],
                default="previewed",
                max_length=20,
            ),
        ),
    ]
